# Generated by Django 3.2.4 on 2021-07-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DsvnDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ja_Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiragana_text', models.CharField(blank=True, default='', max_length=200)),
                ('kanji_text', models.CharField(blank=True, default='', max_length=200)),
                ('katakana_text', models.CharField(blank=True, default='', max_length=200)),
                ('vi_text', models.CharField(blank=True, default='', max_length=200)),
                ('eng_text', models.CharField(blank=True, default='', max_length=200)),
                ('example', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dsvn_dictionary_ja_dictionary',
            },
        ),
        migrations.CreateModel(
            name='Vi_Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_text', models.CharField(default='', max_length=200)),
                ('kanji_text', models.CharField(blank=True, default='', max_length=200)),
                ('hiragana_text', models.CharField(blank=True, default='', max_length=200)),
                ('katakana_text', models.CharField(blank=True, default='', max_length=200)),
                ('eng_text', models.CharField(blank=True, default='', max_length=200)),
                ('example', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dsvn_dictionary_vi_dictionary',
            },
        ),
    ]
