# Generated by Django 3.2.4 on 2021-07-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsvn_dictionary', '0002_auto_20210712_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ja_dictionary',
            name='eng_text',
        ),
        migrations.RemoveField(
            model_name='vi_dictionary',
            name='eng_text',
        ),
    ]
