# Generated by Django 3.2.4 on 2021-07-07 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dsvn_dictionary', '0006_auto_20210706_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='vi_dictionary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
