# Generated by Django 3.2.4 on 2021-07-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsvn_dictionary', '0008_ja_dictionary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ja_dictionary',
            table='ja_dictionary',
        ),
    ]
