# Generated by Django 3.2.4 on 2021-07-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsvn_dictionary', '0009_alter_ja_dictionary_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ja_dictionary',
            table=None,
        ),
    ]
